site_name: Virtual Network Threat Detection
site_description: Containerlab-based network threat detection
site_author: Marc Chamorro
site_url: https://marc-chamorro.github.io/virtual-network-threat-detection/

repo_url: https://github.com/Marc-Chamorro/virtual-network-threat-detection
repo_name: Marc-Chamorro/virtual-network-threat-detection
edit_uri: edit/main/docs/

nav:
  # Welcome users with a homepage that provides an overview of the project. This page should set the tone and context for the documentation.
  - Home: index.md
  # A brief description of the project's purpose, key features, and goals. Understand what the project is and what it aims to solve or achieve.
  - Introduction: introduction.md
  # Outline any requirements or dependencies needed before getting started, such as system requirements, tools, or libraries. This lets users know if they need anything installed beforehand.
  # Provide a simple set of steps or commands for getting the project up and running. This might include installation commands, running the project, or testing basic functionality to get the user started quickly.
  # For example prerequisites, downloading the image
  - Getting Started: getting-started.md
  # A detailed guide on how to install and set up the project. This section should cover all necessary steps, configurations, and options available during installation.
  - Installation: installation.md
  - Usage: usage.md

  - Architecture:
      # Topology design and components used, devices, rules applied, communication, data flow, etc.
      - Overview: architecture/index.md
      - Network Design: architecture/network-design.md
      - Addressing & VLANs: architecture/addressing.md
      - Traffic Flows: architecture/traffic-flows.md

  - Docker & Containerlab:
    # General overview of Docker and its relevance to the project. 
    - Overview: docker/index.md
    # Provided images, how to build them
    - Image Catalog: docker/images.md
    - Dockerfile Standards: docker/dockerfiles.md
    - Entrypoints & Behavior: docker/entrypoint.md
    - External Images: docker/supported-images.md

  - Labs:
    # Detailes information about topology files and lab configurations.
    - Overview: labs/index.md
    - Topology File: labs/topologies.md
    - Lab Configuration: labs/configuration.md

  - Scripts & Automation:
    # Information about any scripts or automation tools included in the project.
    - Overview: scripts/index.md
    - Images Management: scripts/images-management.md
    - Lab Management: scripts/lab-management.md
    - ML Scripts: scripts/ml.md
    - Attack Simulations:
      - Overview: scripts/attacks/index.md
      - Port Scanning: scripts/attacks/port_scanning.md
      - TCP SYN Flood: scripts/attacks/dos_syn_flood_hping3.md
      - Slow HTTP DoS: scripts/attacks/dos_slow_http_slowloris.md
      - SSH Brute Force: scripts/attacks/ssh_bruteforce_hydra.md
      - OSPF Route Hijack: scripts/attacks/ospf_route_hijack.md
      - SMTP Recon + Relay Abuse: scripts/attacks/smtp_recon_abuse.md
      - Dataset Generation: scripts/attacks/generate_traffic.md

  - Network Services:
    - Overview: network-services/index.md
    - DHCP:
      - Design: network-services/dhcp/design.md
      - Server Configuration: network-services/dhcp/server.md
      - Relay Configuration: network-services/dhcp/relay.md
      - Client Behavior: network-services/dhcp/clients.md
    - DNS:
      - Design: network-services/dns/design.md
      - Configuration: network-services/dns/config.md
      - Resolution Flow: network-services/dns/flow.md

  - Services:
    # Overview of the services used in the project, their purpose, and how they interact with each other.
    - Overview: services/index.md
    - WEB: services/web.md
    - SSH: services/ssh.md
    - FTP: services/ftp.md
    - MAIL: services/mail.md
    # - Suricata: services/suricata.md # Mayber here or somewhere else?
    # - Monitoring: services/monitoring.md

  - Monitoring:
    - Overview: monitoring/index.md
    - Suricata: monitoring/suricata.md
    - Elasticsearch: monitoring/elasticsearch.md
    - Filebeat: monitoring/filebeat.md
    - Kibana: monitoring/kibana.md
    - Alerts & Detection Rules (≈ SIEM): monitoring/alerts.md

  - Machine Learning:
    - Overview: ml/index.md
    - Data: ml/data.md
    - Models: ml/models.md
    - Noteook: ml/notebook.md
    - Setup: ml/setup.md

  - Operations & Troubleshooting: operations/commands.md
    # - Useful Commands: operations/commands.md
    # - Debugging Network Issues: operations/debugging.md
    
  # - Cool Examples: example_elements.md

theme:
  name: material
  language: en
  #logo: assets/logo.svg
  #favicon: assets/favicon.svg

  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    #- navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.indexes

    #- toc.integrate
    - toc.follow

    - content.code.copy
    - content.action.edit
    - content.action.view
    - search.highlight
    - search.suggest

    - content.print

    #- content.tabs.link
    #- content.tooltips
    #- content.print

plugins:
  - search
  
  - git-revision-date-localized

  - with-pdf:
      author: Marc Chamorro
      cover_title: Virtual Network Threat Detection
      cover_subtitle: Network Threat Detection Laboratory
      toc_level: 3
      ordered_chapter_level: 2
      output_path: assets/pdf/vntd-docs.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
  
  #- with-pdf:
  #    author: Marc Chamorro
  #    cover_subtitle: Virtual Network Threat Detection Lab
  #    output_path: assets/pdf/vntd-docs.pdf
  #    enabled_if_env: ENABLE_PDF
  #- print-site:
  #  add_to_navigation: false
  #  print_page_title: "Virtual Network Threat Detection"
  #  output_path: assets/pdf/vntd-docs.pdf
  # https://github.com/adrienbrignon/mkdocs-exporter

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Marc-Chamorro

extra_css:
  - assets/stylesheets/pdf.css
