# default to using syslog. /etc/rsyslog.d/45-frr.conf places the log in
# /var/log/frr/frr.log
#
# Note:
# FRR's configuration shell, vtysh, dynamically edits the live, in-memory
# configuration while FRR is running. When instructed, vtysh will persist the
# live configuration to this file, overwriting its contents. If you want to
# avoid this, you can edit this file manually before starting FRR, or instruct
# vtysh to write configuration to a different file.
# log syslog informational

frr version 8.4.4
frr defaults traditional

hostname router-enterprise

log syslog informational

no ipv6 forwarding

# Configure the FRR to advertise the network to the internet
# More details available in: https://docs.frrouting.org/en/latest/ospfd.html
router ospf
 passive-interface default
 no passive-interface eth1
 network 172.16.30.0/30 area 0
